# Not used yet, since match alignment would break due rustfmt not preserving it
edition                      = "2024"
group_imports                = "StdExternalCrate"
imports_granularity          = "Crate"
match_block_trailing_comma   = true
max_width                    = 200
newline_style                = "Unix"
struct_field_align_threshold = 32
trailing_comma               = "Never"
unstable_features            = true
